version: 1.2
workflows:
 - name: viral_refbased_assembly
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_viral_refbased_assembly.wdl
 - name: sc2_pubRepo_submission
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_sc2_pubRepo_submission.wdl
 - name: clearlabs_viral_refbased_assembly
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_clearlabs_viral_refbased_assembly.wdl
 - name: ont_sc2_pubRepo_submission
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_ont_sc2_pubRepo_submission.wdl
 - name: genomic_cluster_analysis
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_genomic_cluster_analysis.wdl
 - name: sc2_batch_submission
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_sc2_batch_submission.wdl
 - name: terra_data_pull
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_terra_data_pull.wdl
 - name: WNV_refbased_assembly
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_WNV_refbased_assembly.wdl
 - name: sphl_lims_prep
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_sphl_lims_prep.wdl
 - name: sphl_lims_file_gen
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_lims_file_gen.wdl
 - name: terra_table_to_csv
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_terra_table_to_csv.wdl

