version: 1.2
workflows:
 - name: viral_refbased_assembly
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_viral_refbased_assembly.wdl
 - name: sc2_pubRepo_submission
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_sc2_pubRepo_submission.wdl
 - name: clear_labs_viral_refbased_assembly
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_clear_labs_viral_refbased_assembly.wdl
 - name: ont_sc2_pubRepo_submission
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_ont_sc2_pubRepo_submission.wdl
